name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Change this to your branch name if necessary
  pull_request:
    branches:
      - main  # Change this to your branch name if necessary

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to other runners if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assumes you have a requirements.txt file

    - name: Run pytest
      run: |
        pytest --maxfail=1 --disable-warnings -v  # Customize pytest options if needed
